FROM golang:1.25-alpine

# Install development tools
RUN apk add --no-cache curl && \
    go install github.com/air-verse/air@v1.64.4 && \
    curl -L https://github.com/golang-migrate/migrate/releases/download/v4.19.1/migrate.linux-amd64.tar.gz | tar xvz && \
    mv migrate /usr/local/bin/migrate && \
    chmod +x /usr/local/bin/migrate && \
    go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.30.0

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

EXPOSE 8080

# Air will be run via docker-compose command
CMD ["air", "-c", ".air.toml"]
