// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: exercises.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const CreateExercise = `-- name: CreateExercise :one
INSERT INTO exercises (
  name, description, body_part
) VALUES (
  $1, $2, $3
)
RETURNING id, name, description, body_part, created_at, updated_at
`

type CreateExerciseParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	BodyPart    sql.NullString `json:"body_part"`
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, CreateExercise, arg.Name, arg.Description, arg.BodyPart)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BodyPart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteExercise = `-- name: DeleteExercise :exec
DELETE FROM exercises
WHERE id = $1
`

func (q *Queries) DeleteExercise(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteExercise, id)
	return err
}

const GetExercise = `-- name: GetExercise :one
SELECT id, name, description, body_part, created_at, updated_at FROM exercises
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetExercise(ctx context.Context, id uuid.UUID) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, GetExercise, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BodyPart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetExerciseByName = `-- name: GetExerciseByName :one
SELECT id, name, description, body_part, created_at, updated_at FROM exercises
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetExerciseByName(ctx context.Context, name string) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, GetExerciseByName, name)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BodyPart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListExercises = `-- name: ListExercises :many
SELECT id, name, description, body_part, created_at, updated_at FROM exercises
ORDER BY name
`

func (q *Queries) ListExercises(ctx context.Context) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, ListExercises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.BodyPart,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListExercisesByBodyPart = `-- name: ListExercisesByBodyPart :many
SELECT id, name, description, body_part, created_at, updated_at FROM exercises
WHERE body_part = $1
ORDER BY name
`

func (q *Queries) ListExercisesByBodyPart(ctx context.Context, bodyPart sql.NullString) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, ListExercisesByBodyPart, bodyPart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.BodyPart,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateExercise = `-- name: UpdateExercise :one
UPDATE exercises
SET name = $2, description = $3, body_part = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, body_part, created_at, updated_at
`

type UpdateExerciseParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	BodyPart    sql.NullString `json:"body_part"`
}

func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, UpdateExercise,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.BodyPart,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BodyPart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
