// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Exercise struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	BodyPart    sql.NullString `json:"body_part"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Profile struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	DisplayName string         `json:"display_name"`
	Age         sql.NullInt32  `json:"age"`
	Weight      sql.NullString `json:"weight"`
	Height      sql.NullString `json:"height"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Workout struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
	Date       time.Time      `json:"date"`
	DailyScore int32          `json:"daily_score"`
	Memo       sql.NullString `json:"memo"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type WorkoutSet struct {
	ID              uuid.UUID      `json:"id"`
	WorkoutID       uuid.UUID      `json:"workout_id"`
	ExerciseID      uuid.UUID      `json:"exercise_id"`
	SetNumber       int32          `json:"set_number"`
	Reps            int32          `json:"reps"`
	Weight          string         `json:"weight"`
	Estimated1rm    string         `json:"estimated_1rm"`
	DurationSeconds sql.NullInt32  `json:"duration_seconds"`
	Notes           sql.NullString `json:"notes"`
	CreatedAt       time.Time      `json:"created_at"`
}
