// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const CreateProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
  id, user_id, display_name, age, weight, height, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, display_name, age, weight, height, created_at, updated_at
`

type CreateProfileParams struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	DisplayName string         `json:"display_name"`
	Age         sql.NullInt32  `json:"age"`
	Weight      sql.NullString `json:"weight"`
	Height      sql.NullString `json:"height"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, CreateProfile,
		arg.ID,
		arg.UserID,
		arg.DisplayName,
		arg.Age,
		arg.Weight,
		arg.Height,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Age,
		&i.Weight,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles
WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteProfile, id)
	return err
}

const ExistsProfileByUserID = `-- name: ExistsProfileByUserID :one
SELECT EXISTS(SELECT 1 FROM profiles WHERE user_id = $1)
`

func (q *Queries) ExistsProfileByUserID(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, ExistsProfileByUserID, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const GetProfile = `-- name: GetProfile :one
SELECT id, user_id, display_name, age, weight, height, created_at, updated_at FROM profiles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProfile(ctx context.Context, id uuid.UUID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, GetProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Age,
		&i.Weight,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetProfileByUserID = `-- name: GetProfileByUserID :one
SELECT id, user_id, display_name, age, weight, height, created_at, updated_at FROM profiles
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetProfileByUserID(ctx context.Context, userID uuid.UUID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, GetProfileByUserID, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Age,
		&i.Weight,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET display_name = $2, age = $3, weight = $4, height = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, display_name, age, weight, height, created_at, updated_at
`

type UpdateProfileParams struct {
	ID          uuid.UUID      `json:"id"`
	DisplayName string         `json:"display_name"`
	Age         sql.NullInt32  `json:"age"`
	Weight      sql.NullString `json:"weight"`
	Height      sql.NullString `json:"height"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, UpdateProfile,
		arg.ID,
		arg.DisplayName,
		arg.Age,
		arg.Weight,
		arg.Height,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Age,
		&i.Weight,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
