// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error)
	CreateWorkoutSet(ctx context.Context, arg CreateWorkoutSetParams) (WorkoutSet, error)
	DeleteExercise(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteWorkout(ctx context.Context, id uuid.UUID) error
	DeleteWorkoutSet(ctx context.Context, id uuid.UUID) error
	DeleteWorkoutSetsByWorkout(ctx context.Context, workoutID uuid.UUID) error
	GetExercise(ctx context.Context, id uuid.UUID) (Exercise, error)
	GetExerciseByName(ctx context.Context, name string) (Exercise, error)
	// 各日の最大推定1RMを取得（重量成長グラフ用）
	GetMaxEstimated1RMByExercise(ctx context.Context, arg GetMaxEstimated1RMByExerciseParams) ([]GetMaxEstimated1RMByExerciseRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetWorkout(ctx context.Context, id uuid.UUID) (Workout, error)
	GetWorkoutByUserAndDate(ctx context.Context, arg GetWorkoutByUserAndDateParams) (Workout, error)
	GetWorkoutSet(ctx context.Context, id uuid.UUID) (WorkoutSet, error)
	ListExercises(ctx context.Context) ([]Exercise, error)
	ListExercisesByBodyPart(ctx context.Context, bodyPart sql.NullString) ([]Exercise, error)
	ListUsers(ctx context.Context) ([]User, error)
	// 重量成長グラフ用：特定種目の推定1RMの推移を取得
	ListWorkoutSetsByExercise(ctx context.Context, arg ListWorkoutSetsByExerciseParams) ([]ListWorkoutSetsByExerciseRow, error)
	ListWorkoutSetsByWorkout(ctx context.Context, workoutID uuid.UUID) ([]WorkoutSet, error)
	ListWorkoutsByUser(ctx context.Context, arg ListWorkoutsByUserParams) ([]Workout, error)
	// GitHub風ヒートマップ用：過去365日の運動強度スコアを取得
	ListWorkoutsForHeatmap(ctx context.Context, userID uuid.UUID) ([]ListWorkoutsForHeatmapRow, error)
	UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (Exercise, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateWorkout(ctx context.Context, arg UpdateWorkoutParams) (Workout, error)
	UpdateWorkoutSet(ctx context.Context, arg UpdateWorkoutSetParams) (WorkoutSet, error)
}

var _ Querier = (*Queries)(nil)
