// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (
  email, password_hash, email_verified, verification_token, verification_token_expires_at
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, email, password_hash, email_verified, verification_token, verification_token_expires_at, created_at, updated_at
`

type CreateUserParams struct {
	Email                      string         `json:"email"`
	PasswordHash               string         `json:"password_hash"`
	EmailVerified              bool           `json:"email_verified"`
	VerificationToken          sql.NullString `json:"verification_token"`
	VerificationTokenExpiresAt sql.NullTime   `json:"verification_token_expires_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, CreateUser,
		arg.Email,
		arg.PasswordHash,
		arg.EmailVerified,
		arg.VerificationToken,
		arg.VerificationTokenExpiresAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteUser, id)
	return err
}

const GetUser = `-- name: GetUser :one
SELECT id, email, password_hash, email_verified, verification_token, verification_token_expires_at, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, GetUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, email_verified, verification_token, verification_token_expires_at, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, GetUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetUserByVerificationToken = `-- name: GetUserByVerificationToken :one
SELECT id, email, password_hash, email_verified, verification_token, verification_token_expires_at, created_at, updated_at FROM users
WHERE verification_token = $1 LIMIT 1
`

func (q *Queries) GetUserByVerificationToken(ctx context.Context, verificationToken sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, GetUserByVerificationToken, verificationToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, email_verified, verification_token, verification_token_expires_at, created_at, updated_at FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, ListUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.EmailVerified,
			&i.VerificationToken,
			&i.VerificationTokenExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, password_hash = $3, email_verified = $4, verification_token = $5, verification_token_expires_at = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, email, password_hash, email_verified, verification_token, verification_token_expires_at, created_at, updated_at
`

type UpdateUserParams struct {
	ID                         uuid.UUID      `json:"id"`
	Email                      string         `json:"email"`
	PasswordHash               string         `json:"password_hash"`
	EmailVerified              bool           `json:"email_verified"`
	VerificationToken          sql.NullString `json:"verification_token"`
	VerificationTokenExpiresAt sql.NullTime   `json:"verification_token_expires_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, UpdateUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.EmailVerified,
		arg.VerificationToken,
		arg.VerificationTokenExpiresAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
