// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: workouts.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const CreateWorkout = `-- name: CreateWorkout :one
INSERT INTO workouts (
  user_id, date, daily_score, memo
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, date, daily_score, memo, created_at, updated_at
`

type CreateWorkoutParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	Date       time.Time      `json:"date"`
	DailyScore int32          `json:"daily_score"`
	Memo       sql.NullString `json:"memo"`
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, CreateWorkout,
		arg.UserID,
		arg.Date,
		arg.DailyScore,
		arg.Memo,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.DailyScore,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteWorkout = `-- name: DeleteWorkout :exec
DELETE FROM workouts
WHERE id = $1
`

func (q *Queries) DeleteWorkout(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteWorkout, id)
	return err
}

const GetWorkout = `-- name: GetWorkout :one
SELECT id, user_id, date, daily_score, memo, created_at, updated_at FROM workouts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorkout(ctx context.Context, id uuid.UUID) (Workout, error) {
	row := q.db.QueryRowContext(ctx, GetWorkout, id)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.DailyScore,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetWorkoutByUserAndDate = `-- name: GetWorkoutByUserAndDate :one
SELECT id, user_id, date, daily_score, memo, created_at, updated_at FROM workouts
WHERE user_id = $1 AND date = $2 LIMIT 1
`

type GetWorkoutByUserAndDateParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
}

func (q *Queries) GetWorkoutByUserAndDate(ctx context.Context, arg GetWorkoutByUserAndDateParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, GetWorkoutByUserAndDate, arg.UserID, arg.Date)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.DailyScore,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListAllWorkoutsByUser = `-- name: ListAllWorkoutsByUser :many
SELECT id, user_id, date, daily_score, memo, created_at, updated_at FROM workouts
WHERE user_id = $1
ORDER BY date DESC
`

func (q *Queries) ListAllWorkoutsByUser(ctx context.Context, userID uuid.UUID) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, ListAllWorkoutsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workout{}
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.DailyScore,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListWorkoutsByUser = `-- name: ListWorkoutsByUser :many
SELECT id, user_id, date, daily_score, memo, created_at, updated_at FROM workouts
WHERE user_id = $1
ORDER BY date DESC
LIMIT $2 OFFSET $3
`

type ListWorkoutsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListWorkoutsByUser(ctx context.Context, arg ListWorkoutsByUserParams) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, ListWorkoutsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workout{}
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.DailyScore,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListWorkoutsByUserAndDateRange = `-- name: ListWorkoutsByUserAndDateRange :many
SELECT id, user_id, date, daily_score, memo, created_at, updated_at FROM workouts
WHERE user_id = $1 AND date >= $2 AND date <= $3
ORDER BY date DESC
`

type ListWorkoutsByUserAndDateRangeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date_2"`
}

func (q *Queries) ListWorkoutsByUserAndDateRange(ctx context.Context, arg ListWorkoutsByUserAndDateRangeParams) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, ListWorkoutsByUserAndDateRange, arg.UserID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workout{}
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.DailyScore,
			&i.Memo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListWorkoutsForHeatmap = `-- name: ListWorkoutsForHeatmap :many
SELECT date, daily_score
FROM workouts
WHERE user_id = $1
  AND date >= CURRENT_DATE - INTERVAL '365 days'
ORDER BY date
`

type ListWorkoutsForHeatmapRow struct {
	Date       time.Time `json:"date"`
	DailyScore int32     `json:"daily_score"`
}

// GitHub風ヒートマップ用：過去365日の運動強度スコアを取得
func (q *Queries) ListWorkoutsForHeatmap(ctx context.Context, userID uuid.UUID) ([]ListWorkoutsForHeatmapRow, error) {
	rows, err := q.db.QueryContext(ctx, ListWorkoutsForHeatmap, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkoutsForHeatmapRow{}
	for rows.Next() {
		var i ListWorkoutsForHeatmapRow
		if err := rows.Scan(&i.Date, &i.DailyScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateWorkout = `-- name: UpdateWorkout :one
UPDATE workouts
SET daily_score = $2, memo = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, date, daily_score, memo, created_at, updated_at
`

type UpdateWorkoutParams struct {
	ID         uuid.UUID      `json:"id"`
	DailyScore int32          `json:"daily_score"`
	Memo       sql.NullString `json:"memo"`
}

func (q *Queries) UpdateWorkout(ctx context.Context, arg UpdateWorkoutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, UpdateWorkout, arg.ID, arg.DailyScore, arg.Memo)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.DailyScore,
		&i.Memo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
