// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: workout_sets.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const CreateWorkoutSet = `-- name: CreateWorkoutSet :one
INSERT INTO workout_sets (
  workout_id, exercise_id, set_number, reps, weight, estimated_1rm, duration_seconds, notes
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, workout_id, exercise_id, set_number, reps, weight, estimated_1rm, duration_seconds, notes, created_at
`

type CreateWorkoutSetParams struct {
	WorkoutID       uuid.UUID      `json:"workout_id"`
	ExerciseID      uuid.UUID      `json:"exercise_id"`
	SetNumber       int32          `json:"set_number"`
	Reps            int32          `json:"reps"`
	Weight          string         `json:"weight"`
	Estimated1rm    string         `json:"estimated_1rm"`
	DurationSeconds sql.NullInt32  `json:"duration_seconds"`
	Notes           sql.NullString `json:"notes"`
}

func (q *Queries) CreateWorkoutSet(ctx context.Context, arg CreateWorkoutSetParams) (WorkoutSet, error) {
	row := q.db.QueryRowContext(ctx, CreateWorkoutSet,
		arg.WorkoutID,
		arg.ExerciseID,
		arg.SetNumber,
		arg.Reps,
		arg.Weight,
		arg.Estimated1rm,
		arg.DurationSeconds,
		arg.Notes,
	)
	var i WorkoutSet
	err := row.Scan(
		&i.ID,
		&i.WorkoutID,
		&i.ExerciseID,
		&i.SetNumber,
		&i.Reps,
		&i.Weight,
		&i.Estimated1rm,
		&i.DurationSeconds,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteWorkoutSet = `-- name: DeleteWorkoutSet :exec
DELETE FROM workout_sets
WHERE id = $1
`

func (q *Queries) DeleteWorkoutSet(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteWorkoutSet, id)
	return err
}

const DeleteWorkoutSetsByWorkout = `-- name: DeleteWorkoutSetsByWorkout :exec
DELETE FROM workout_sets
WHERE workout_id = $1
`

func (q *Queries) DeleteWorkoutSetsByWorkout(ctx context.Context, workoutID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteWorkoutSetsByWorkout, workoutID)
	return err
}

const GetMaxEstimated1RMByExercise = `-- name: GetMaxEstimated1RMByExercise :many
SELECT
  w.date,
  MAX(ws.estimated_1rm) as max_1rm
FROM workouts w
JOIN workout_sets ws ON w.id = ws.workout_id
WHERE w.user_id = $1 AND ws.exercise_id = $2
GROUP BY w.date
ORDER BY w.date
`

type GetMaxEstimated1RMByExerciseParams struct {
	UserID     uuid.UUID `json:"user_id"`
	ExerciseID uuid.UUID `json:"exercise_id"`
}

type GetMaxEstimated1RMByExerciseRow struct {
	Date   time.Time   `json:"date"`
	Max1rm interface{} `json:"max_1rm"`
}

// 各日の最大推定1RMを取得（重量成長グラフ用）
func (q *Queries) GetMaxEstimated1RMByExercise(ctx context.Context, arg GetMaxEstimated1RMByExerciseParams) ([]GetMaxEstimated1RMByExerciseRow, error) {
	rows, err := q.db.QueryContext(ctx, GetMaxEstimated1RMByExercise, arg.UserID, arg.ExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMaxEstimated1RMByExerciseRow{}
	for rows.Next() {
		var i GetMaxEstimated1RMByExerciseRow
		if err := rows.Scan(&i.Date, &i.Max1rm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetOverallMaxEstimated1RMByExerciseAndUser = `-- name: GetOverallMaxEstimated1RMByExerciseAndUser :one
SELECT COALESCE(MAX(ws.estimated_1rm), '0')::text as max_1rm
FROM workout_sets ws
JOIN workouts w ON ws.workout_id = w.id
WHERE w.user_id = $1 AND ws.exercise_id = $2
`

type GetOverallMaxEstimated1RMByExerciseAndUserParams struct {
	UserID     uuid.UUID `json:"user_id"`
	ExerciseID uuid.UUID `json:"exercise_id"`
}

// 全期間の最大推定1RMを取得
func (q *Queries) GetOverallMaxEstimated1RMByExerciseAndUser(ctx context.Context, arg GetOverallMaxEstimated1RMByExerciseAndUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, GetOverallMaxEstimated1RMByExerciseAndUser, arg.UserID, arg.ExerciseID)
	var max_1rm string
	err := row.Scan(&max_1rm)
	return max_1rm, err
}

const GetWorkoutSet = `-- name: GetWorkoutSet :one
SELECT id, workout_id, exercise_id, set_number, reps, weight, estimated_1rm, duration_seconds, notes, created_at FROM workout_sets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorkoutSet(ctx context.Context, id uuid.UUID) (WorkoutSet, error) {
	row := q.db.QueryRowContext(ctx, GetWorkoutSet, id)
	var i WorkoutSet
	err := row.Scan(
		&i.ID,
		&i.WorkoutID,
		&i.ExerciseID,
		&i.SetNumber,
		&i.Reps,
		&i.Weight,
		&i.Estimated1rm,
		&i.DurationSeconds,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const ListWorkoutSetsByExercise = `-- name: ListWorkoutSetsByExercise :many
SELECT
  ws.id,
  ws.workout_id,
  ws.exercise_id,
  ws.set_number,
  ws.reps,
  ws.weight,
  ws.estimated_1rm,
  ws.duration_seconds,
  ws.notes,
  ws.created_at,
  w.date as workout_date
FROM workout_sets ws
JOIN workouts w ON ws.workout_id = w.id
WHERE w.user_id = $1 AND ws.exercise_id = $2
ORDER BY w.date DESC, ws.set_number
`

type ListWorkoutSetsByExerciseParams struct {
	UserID     uuid.UUID `json:"user_id"`
	ExerciseID uuid.UUID `json:"exercise_id"`
}

type ListWorkoutSetsByExerciseRow struct {
	ID              uuid.UUID      `json:"id"`
	WorkoutID       uuid.UUID      `json:"workout_id"`
	ExerciseID      uuid.UUID      `json:"exercise_id"`
	SetNumber       int32          `json:"set_number"`
	Reps            int32          `json:"reps"`
	Weight          string         `json:"weight"`
	Estimated1rm    string         `json:"estimated_1rm"`
	DurationSeconds sql.NullInt32  `json:"duration_seconds"`
	Notes           sql.NullString `json:"notes"`
	CreatedAt       time.Time      `json:"created_at"`
	WorkoutDate     time.Time      `json:"workout_date"`
}

// 重量成長グラフ用：特定種目の推定1RMの推移を取得
func (q *Queries) ListWorkoutSetsByExercise(ctx context.Context, arg ListWorkoutSetsByExerciseParams) ([]ListWorkoutSetsByExerciseRow, error) {
	rows, err := q.db.QueryContext(ctx, ListWorkoutSetsByExercise, arg.UserID, arg.ExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkoutSetsByExerciseRow{}
	for rows.Next() {
		var i ListWorkoutSetsByExerciseRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.ExerciseID,
			&i.SetNumber,
			&i.Reps,
			&i.Weight,
			&i.Estimated1rm,
			&i.DurationSeconds,
			&i.Notes,
			&i.CreatedAt,
			&i.WorkoutDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListWorkoutSetsByExerciseID = `-- name: ListWorkoutSetsByExerciseID :many
SELECT id, workout_id, exercise_id, set_number, reps, weight, estimated_1rm, duration_seconds, notes, created_at FROM workout_sets
WHERE exercise_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWorkoutSetsByExerciseID(ctx context.Context, exerciseID uuid.UUID) ([]WorkoutSet, error) {
	rows, err := q.db.QueryContext(ctx, ListWorkoutSetsByExerciseID, exerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkoutSet{}
	for rows.Next() {
		var i WorkoutSet
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.ExerciseID,
			&i.SetNumber,
			&i.Reps,
			&i.Weight,
			&i.Estimated1rm,
			&i.DurationSeconds,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListWorkoutSetsByWorkout = `-- name: ListWorkoutSetsByWorkout :many
SELECT id, workout_id, exercise_id, set_number, reps, weight, estimated_1rm, duration_seconds, notes, created_at FROM workout_sets
WHERE workout_id = $1
ORDER BY exercise_id, set_number
`

func (q *Queries) ListWorkoutSetsByWorkout(ctx context.Context, workoutID uuid.UUID) ([]WorkoutSet, error) {
	rows, err := q.db.QueryContext(ctx, ListWorkoutSetsByWorkout, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkoutSet{}
	for rows.Next() {
		var i WorkoutSet
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.ExerciseID,
			&i.SetNumber,
			&i.Reps,
			&i.Weight,
			&i.Estimated1rm,
			&i.DurationSeconds,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListWorkoutSetsByWorkoutAndExercise = `-- name: ListWorkoutSetsByWorkoutAndExercise :many
SELECT id, workout_id, exercise_id, set_number, reps, weight, estimated_1rm, duration_seconds, notes, created_at FROM workout_sets
WHERE workout_id = $1 AND exercise_id = $2
ORDER BY set_number
`

type ListWorkoutSetsByWorkoutAndExerciseParams struct {
	WorkoutID  uuid.UUID `json:"workout_id"`
	ExerciseID uuid.UUID `json:"exercise_id"`
}

func (q *Queries) ListWorkoutSetsByWorkoutAndExercise(ctx context.Context, arg ListWorkoutSetsByWorkoutAndExerciseParams) ([]WorkoutSet, error) {
	rows, err := q.db.QueryContext(ctx, ListWorkoutSetsByWorkoutAndExercise, arg.WorkoutID, arg.ExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkoutSet{}
	for rows.Next() {
		var i WorkoutSet
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.ExerciseID,
			&i.SetNumber,
			&i.Reps,
			&i.Weight,
			&i.Estimated1rm,
			&i.DurationSeconds,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateWorkoutSet = `-- name: UpdateWorkoutSet :one
UPDATE workout_sets
SET reps = $2, weight = $3, estimated_1rm = $4, duration_seconds = $5, notes = $6
WHERE id = $1
RETURNING id, workout_id, exercise_id, set_number, reps, weight, estimated_1rm, duration_seconds, notes, created_at
`

type UpdateWorkoutSetParams struct {
	ID              uuid.UUID      `json:"id"`
	Reps            int32          `json:"reps"`
	Weight          string         `json:"weight"`
	Estimated1rm    string         `json:"estimated_1rm"`
	DurationSeconds sql.NullInt32  `json:"duration_seconds"`
	Notes           sql.NullString `json:"notes"`
}

func (q *Queries) UpdateWorkoutSet(ctx context.Context, arg UpdateWorkoutSetParams) (WorkoutSet, error) {
	row := q.db.QueryRowContext(ctx, UpdateWorkoutSet,
		arg.ID,
		arg.Reps,
		arg.Weight,
		arg.Estimated1rm,
		arg.DurationSeconds,
		arg.Notes,
	)
	var i WorkoutSet
	err := row.Scan(
		&i.ID,
		&i.WorkoutID,
		&i.ExerciseID,
		&i.SetNumber,
		&i.Reps,
		&i.Weight,
		&i.Estimated1rm,
		&i.DurationSeconds,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
