import React from "react";
import type { Metadata } from "next";
import { Box, Container } from "@mui/material";
import { Providers } from "@/app/components/Providers";
import { NavigationBar } from "./components/NavigationBar";
import { TabNavigation } from "./components/TabNavigation/TabNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavigationBar />
          <Box component="main" sx={{ paddingTop: "64px" }}>
            <TabNavigation />
            <Container sx={{ mt: 3 }}>
              {children}
            </Container>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
