name: リファクタリング / 技術改善
description: コード品質の改善や技術的負債の解消を提案する
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        リファクタリングや技術改善の提案ありがとうございます。
  - type: dropdown
    id: area
    attributes:
      label: 対象領域
      options:
        - フロントエンド
        - バックエンド
        - インフラ / DevOps
        - テスト
        - その他
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: 現状の問題
      description: 現在のコードや設計の何が問題かを説明してください
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 改善案
      description: どのように改善するかを説明してください
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: 影響範囲
      description: この変更が影響するファイルや機能を記述してください
    validations:
      required: false
